### ISSUE TITLE
lags after 3rd level

### ISSUE THREAD

**Issue by bam** [weslleyaraujo/react-simon-says#1]
From the first level and forth performance decreases. It becomes noticeable from 3rd level already. At the 8th level it works so slow that I afraid I can fall asleep while listen till the end...
I've checked, it loads 1 of 8 virtual cores to the 100% when playing sounds. At 3.5 GHz! Whoa! 3.5 GHz for game of 4 buttons!
Tested on 2 browsers. Firstly I thought Microsoft Edge is far from ideal browser. But Goggle chrome had the same issues.
Maybe my gaming laptop of 2015 is not performant for this game? =)))
If I will have free time earlier than you, I will try to investigate, and than fork and fix...

**Comment by weslleyaraujo** [comment]
Hey! that's an old issue here hehe

Yes it seemed like there was a memory leak somewhere, I fixed by updating the project deps and changing a few things on how the Board component reads the redux store 😬

Thanks you for opening this!
